# Generated by Django 5.2.3 on 2025-06-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='chat_id',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Telegram chat ID'),
        ),
    ]
